### ISSUE TITLE
Multiple tests fail to run correctly when tenant has a privileged Group with access into the tenant via a GDAP relationship

### ISSUE THREAD

**Issue by mattcave** [maester365/maester#521] opened 2024-11-06 01:14 UTC
We work with a number of tenants who have GDAP relationships with multiple vendors (e.g. a vendor that they buy MS licences from). If that GDAP relationship includes the role **Global Administrator**, a number of tests will fail to run correctly. This is because the call to `Get-MtRoleMember` will result in a 404 error - the code tries to make a Graph call to https://graph.microsoft.com/v1.0/groups/<group_id>/members but that call (correctly) returns a 404 as that object is not part of the target tenant. 

I'm not sure what the correct behaviour is in this scenario. 

* Having a Global Admin role on the GDAP relationship is not a good practice, but it's allowed and shouldn't cause the test to throw an error.
* That said, if we cannot pull the details for that group, the test cannot pass because it won't have the information to make a determination.

Perhaps the best course of action is to provide better info about why the test is failing (ie we can't pull all the info we need)?

I believe this affects all MS.AAD.7.x tests

**Comment by soulemike** [comment] 2024-11-06 15:54
MS.AAD.7.1 with Direct and Indirect reseller relationship setup, without any role delegations (i.e., Legacy DAP). The tests run successfully.
![image](https://github.com/user-attachments/assets/14be4d9f-b90a-46cc-bef3-5733373f8ecd)
![image](https://github.com/user-attachments/assets/067f4b32-abf4-4385-a0e6-f993e0f172ba)

Will get access to generate a GDAP relationship for my test environment later and test again, as that will likely be the culprit. Just documenting different scenarios to identify scope.

**Comment by mattcave** [comment] 2024-11-06 16:11
![Screenshot 2024-11-06 at 11 08 40 AM](https://github.com/user-attachments/assets/7c89c756-5def-4b19-805c-9327572e9e8d)
Example of a configuration that we see causing an error, to help you with reproducing the issue.

**Comment by soulemike** [comment] 2024-11-07 21:49
A test with Global Reader

![image](https://github.com/user-attachments/assets/aae8eb54-1d76-42fb-89cd-4cdecae8614a)
![image](https://github.com/user-attachments/assets/ea954e46-cac0-4037-b10a-56a16769b5cf)


A test with Global Admin

![image](https://github.com/user-attachments/assets/b565951e-45e3-475a-9cc6-ee6f9a377dd7)
![image](https://github.com/user-attachments/assets/21b4425b-5a92-4d87-b6b7-3433b309cda5)


@mattcave do you have a few more examples on maybe narrowing down this?

**Comment by mattcave** [comment] 2024-11-07 22:58
There's one more key factor that I didn't include in my initial report. Apologies. 

We are authenticating to Graph using delegated access via GDAP. In the screenshot I shared before, we are `Augmentt-aef7f162-1724159588768`. So we are a CSP "parent", and we are running Maester tests against the "child" tenant. The problem is when there is _another_ CSP parent with GA role on the child tenant.

Does that make sense?

**Comment by mattcave** [comment] 2024-11-08 22:04
Did further testing today, and the way we are accessing the problem tenant is not relevant. I get the same error if I `Connect-Maester` for that tenant interactively from command line. 

It also seems that the GDAP relationship does not need to include the GA role in order to trigger this issue. I have a GDAP relationship that includes a number of other lesser-privileged roles that still experiences the error.

For example running MS.AAD.7.2 on this tenant...

1. We run `Get-MtRole -CisaHighlyPrivilegedRoles` to get the list of Privileged roles (8 in this case)
2. We then `Get-MtRoleMember` for each Role
3. For the first role (Global Admin), we find 6 users in the tenant with the GA role assigned.
4. For the second role (User Admin), we get a single group that is the AdminAgents group from a CSP parent tenant.
5. When we run `Get-MtGroupMember` against that Group, it fails with a 404 error. 

Trying to get group memberships for a group that has delegated access into the tenant from a "parent" tenant will result in a 404, and hence the test will fail.

I have reproduced this in a test environment, and can share credentials if it helps understand the issue.

**Comment by soulemike** [comment] 2024-11-14 15:12
> For the second role (User Admin), we get a single group that is the AdminAgents group from a CSP parent tenant.
> When we run Get-MtGroupMember against that Group, it fails with a 404 error.

This definitely makes sense. As that AdminAgents group would be in a distinct tenant. So is the issue the test skips or fails in the report, or is it just for the `Get-MtGroupMember` that 404s? I wouldn't expect a client tenant to ever be able to resolve the members of the CSP's AdminAgents group.

> Trying to get group memberships for a group that has delegated access into the tenant from a "parent" tenant will result in a 404, and hence the test will fail.

As for logging in to tenants interactively over GDAP to run tests, I would definitely avoid that. The recommendation would be to use an Enterprise App in the client tenant that is based on the App Reg in your tenant. The main reasoning is that the GDAP capabilities will vary for each API and SDK.

**Comment by mattcave** [comment] 2024-11-14 15:21
The issue is that the test **fails** as a result of that 404 error I mentioned. I'm not sure what the correct behaviour should be. Fail with an explanation, because we will never be able to tell if the configuration is "Safe" or not? List the unresolvable groups in the test details?

> As for logging in to tenants interactively over GDAP to run tests, I would definitely avoid that. The recommendation would be to use an Enterprise App in the client tenant that is based on the App Reg in your tenant. The main reasoning is that the GDAP capabilities will vary for each API and SDK.

Yeh, that's what we're doing. I did that interactive login purely for testing purposes in our QA environment, to eliminate any weirdness as a result of how we're generating the token, and ensure I 100% understand the root cause of the issue.

**Comment by soulemike** [comment] 2024-11-14 17:00
I am having an AOBO mapping configured for my test environment. Since the issue isn't with GDAP relationships but rather the AOBO group membership enumeration. @mattcave if you have ideas on how to identify and exclude the AOBO groups feel free to work on a PR. Otherwise I will plan to test and try to identify a solution.

**Comment by soulemike** [comment] 2024-12-12 12:21
I believe this should be resolved @mattcave. I will close this, thank you for the feedback on this. For now the AOBO groups are noted in the console error messages that they can not be found, but this allows the test to still run fully.

**Closed by soulemike** 2024-12-12 12:21 UTC
